const SYNC_DB='rikkyo-uk-kokugo-progress-sync';
const SYNC_DB_VERSION=7;
const APP_ID='rikkyo-uk-kokugo';
const MAX_BATCH=10;
const FLUSH_DELAY_MS=5000;
const RECONCILE_INTERVAL_MS=5*60*1000;
const REQUEST_TIMEOUT_MS=15000;
const MAX_BACKOFF_MS=60000;
const UNKNOWN_OCCURRED_AT='1970-01-01T00:00:00.000Z';
const te=new TextEncoder();
let initPromise=null,baselineProvider=null,scannerStarted=false,flushTimer=null,flushInFlight=null,flushAgain=false,flushBackoff=1000;

function apiBase(){const env=typeof import.meta!=='undefined'?import.meta.env?.VITE_PROGRESS_API_BASE:'';const win=typeof window!=='undefined'?window.__RIKKYO_UK_KOKUGO_PROGRESS_API__ : '';return String(env||win||'').replace(/\/+$/,'');}
function canonicalize(v){if(Array.isArray(v))return v.map(canonicalize);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonicalize(v[k])]));return v;}
const canonicalJson=v=>JSON.stringify(canonicalize(v));
async function sha256Hex(v){const d=await crypto.subtle.digest('SHA-256',te.encode(String(v)));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function randomToken(bytes=32){const a=new Uint8Array(bytes);crypto.getRandomValues(a);let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
async function fetchWithTimeout(url,options={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:c.signal});}finally{clearTimeout(t);}}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(SYNC_DB,SYNC_DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('control'))db.createObjectStore('control',{keyPath:'key'});if(!db.objectStoreNames.contains('outbox'))db.createObjectStore('outbox',{keyPath:'eventId'});if(!db.objectStoreNames.contains('deadletter'))db.createObjectStore('deadletter',{keyPath:'eventId'});if(!db.objectStoreNames.contains('seen_v2'))db.createObjectStore('seen_v2',{keyPath:'sourceKey'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('progress sync database blocked'));});}
function txDone(tx){return new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error||new Error('transaction aborted'));});}
async function requestValue(req){return new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error);});}
async function getControl(key){const db=await openDb();try{const tx=db.transaction('control','readonly'),row=await requestValue(tx.objectStore('control').get(key));await txDone(tx);return row?.value;}finally{db.close();}}
async function setControl(key,value){const db=await openDb();try{const tx=db.transaction('control','readwrite'),s=tx.objectStore('control');value==null?s.delete(key):s.put({key,value});await txDone(tx);}finally{db.close();}}
function sourceKey(id){return `${APP_ID}:${String(id)}`;}
function enrollmentTokenFromHash(){return typeof location==='undefined'?'':new URLSearchParams(location.hash.replace(/^#/,'')).get('enroll')||'';}
function clearEnrollmentHash(){if(typeof history==='undefined'||typeof location==='undefined')return;const p=new URLSearchParams(location.hash.replace(/^#/,''));p.delete('enroll');history.replaceState(null,'',`${location.pathname}${location.search}${p.toString()?`#${p}`:''}`);}
async function persistEnrollmentTokenFromHash(){const token=enrollmentTokenFromHash();if(!token)return await getControl('pendingEnrollmentToken');let pending=await getControl('pendingEnrollmentToken');if(!pending?.token||pending.token!==token){pending={token,storedAt:new Date().toISOString()};await setControl('pendingEnrollmentToken',pending);}clearEnrollmentHash();return pending;}
function deviceMetadata(){const ua=String(navigator.userAgent||'');return{deviceType:/iPad|Tablet/i.test(ua)?'tablet':/Mobi|Android|iPhone/i.test(ua)?'mobile':'desktop',osFamily:/iPhone|iPad|iOS/i.test(ua)?'iOS/iPadOS':/Android/i.test(ua)?'Android':/Windows/i.test(ua)?'Windows':/Mac OS|Macintosh/i.test(ua)?'macOS':/Linux/i.test(ua)?'Linux':'unknown',browserFamily:/Edg\//i.test(ua)?'Edge':/CriOS|Chrome\//i.test(ua)?'Chrome':/FxiOS|Firefox\//i.test(ua)?'Firefox':/Safari\//i.test(ua)?'Safari':'unknown'};}
function finite(v){const n=Number(v);return Number.isFinite(n)?n:undefined;}
function stableOccurredAt(e){for(const v of[e?.completedAt,e?.finishedAt,e?.createdAt,e?.timestamp,e?.at,e?.savedAt]){const t=Date.parse(String(v||''));if(Number.isFinite(t))return{value:new Date(t).toISOString(),unknown:false};}return{value:UNKNOWN_OCCURRED_AT,unknown:true};}
function summarizeEvent(e){const p={};const put=(k,v)=>{if(v!==undefined&&v!==null&&v!=='')p[k]=v};put('year',e?.year!=null?String(e.year):undefined);put('mode',typeof e?.mode==='string'?e.mode:undefined);put('kind',typeof e?.kind==='string'?e.kind:undefined);put('type',typeof e?.type==='string'?e.type:undefined);put('score',finite(e?.score??e?.totalScore));put('maxScore',finite(e?.maxScore??e?.possibleScore));put('correct',finite(e?.correct??e?.correctCount));put('total',finite(e?.total??e?.questionCount));put('draftId',typeof e?.draftId==='string'?e.draftId:undefined);put('questionId',typeof e?.questionId==='string'?e.questionId:undefined);put('contentVersion',typeof e?.contentVersion==='string'?e.contentVersion:undefined);return p;}
async function eventBase(e){const sourceRecordId=String(e.id),eventType=String(e?.type||e?.kind||e?.mode||'learning-event').slice(0,80),occurred=stableOccurredAt(e),payload=summarizeEvent(e);if(occurred.unknown)payload.clockUnknown=true;const fingerprint=await sha256Hex(canonicalJson({appId:APP_ID,sourceRecordId,eventType,occurredAt:occurred.value,payload}));return{sourceRecordId,sourceHash:await sha256Hex(sourceRecordId),eventType,occurredAt:occurred.value,payload,fingerprint};}
function summarizeBaseline(events=[]){let scored=0,scoreTotal=0;const years={};for(const e of events){if(e?.year!=null)years[String(e.year)]=(years[String(e.year)]||0)+1;const s=finite(e?.score??e?.totalScore);if(s!==undefined){scored++;scoreTotal+=s;}}return{baseline:true,eventCount:events.length,scoredEventCount:scored,scoreTotal,eventsByYear:years,capturedAt:new Date().toISOString()};}
async function captureBaseline(events=[]){const fingerprints=[];for(const e of events){if(!e?.id)continue;const b=await eventBase(e);fingerprints.push({sourceRecordId:b.sourceRecordId,fingerprint:b.fingerprint});}return{summary:summarizeBaseline(events),fingerprints};}
async function createOrGetPendingStub(){const db=await openDb();try{const tx=db.transaction('control','readwrite'),store=tx.objectStore('control'),current=(await requestValue(store.get('pendingRegistration')))?.value;if(current){await txDone(tx);return current;}const pending={registrationId:crypto.randomUUID(),credential:randomToken(),createdAt:new Date().toISOString(),baseline:null,baselineFinalized:false};store.put({key:'pendingRegistration',value:pending});await txDone(tx);return pending;}finally{db.close();}}
async function finalizePendingBaseline(pending){if(pending?.baselineFinalized&&pending?.baseline)return pending;const existing=typeof baselineProvider==='function'?(await baselineProvider())||[]:[];const baseline=await captureBaseline(existing);const db=await openDb();try{const tx=db.transaction('control','readwrite'),store=tx.objectStore('control'),current=(await requestValue(store.get('pendingRegistration')))?.value;if(!current||current.registrationId!==pending.registrationId){await txDone(tx);return current||pending;}if(!current.baselineFinalized){const next={...current,baseline,baselineFinalized:true};store.put({key:'pendingRegistration',value:next});await txDone(tx);return next;}await txDone(tx);return current;}finally{db.close();}}
async function ensurePendingRegistration(){const reg=await getControl('registration');if(reg?.credential)return reg;if(await getControl('syncRevoked'))return null;const stub=await createOrGetPendingStub();return finalizePendingBaseline(stub);}
function baselineContains(pending,base){return Boolean(pending?.baselineFinalized&&pending?.baseline?.fingerprints?.some(row=>String(row.sourceRecordId)===base.sourceRecordId&&row.fingerprint===base.fingerprint));}
async function markBaselineSeen(fingerprints=[]){const db=await openDb();try{const tx=db.transaction('seen_v2','readwrite'),s=tx.objectStore('seen_v2'),at=new Date().toISOString();for(const row of fingerprints){const key=sourceKey(row.sourceRecordId),current=await requestValue(s.get(key));if(!current)s.put({sourceKey:key,appId:APP_ID,sourceRecordId:row.sourceRecordId,state:'baseline',revision:0,fingerprint:row.fingerprint,at});}await txDone(tx);}finally{db.close();}}
async function promoteWithEnrollment(reg){const pendingToken=await persistEnrollmentTokenFromHash();const token=pendingToken?.token;if(!reg?.credential||!token)return false;try{const r=await fetchWithTimeout(`${apiBase()}/v1/enroll`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,registrationId:reg.registrationId,credentialHash:await sha256Hex(reg.credential),device:deviceMetadata()})});const d=await r.json().catch(()=>({}));if(!r.ok){if([400,409].includes(r.status))await setControl('pendingEnrollmentToken',null);return false;}await setControl('registration',{registrationId:reg.registrationId,credential:reg.credential,status:'production',deviceCode:d.deviceCode||reg.deviceCode||null,enrolledAt:new Date().toISOString()});await setControl('pendingEnrollmentToken',null);await setControl('syncRevoked',null);return true;}catch{return false;}}
async function registerSilently(){if(!apiBase()||await getControl('syncRevoked'))return false;await persistEnrollmentTokenFromHash();let reg=await getControl('registration');if(reg?.credential)return (await getControl('pendingEnrollmentToken'))?.token?promoteWithEnrollment(reg):true;const pending=await ensurePendingRegistration();if(!pending)return false;if((await getControl('pendingEnrollmentToken'))?.token)return promoteWithEnrollment(pending);try{const r=await fetchWithTimeout(`${apiBase()}/v1/register-anonymous`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({registrationId:pending.registrationId,credentialHash:await sha256Hex(pending.credential),device:deviceMetadata()})});const d=await r.json().catch(()=>({}));if(!r.ok)return false;await setControl('registration',{registrationId:pending.registrationId,credential:pending.credential,status:d.status||'unclassified',deviceCode:d.deviceCode||null,enrolledAt:new Date().toISOString()});return true;}catch{return false;}}
async function queueEvent(base){const db=await openDb();try{const tx=db.transaction(['outbox','seen_v2'],'readwrite'),seen=tx.objectStore('seen_v2'),key=sourceKey(base.sourceRecordId),current=await requestValue(seen.get(key));if(current?.fingerprint===base.fingerprint){await txDone(tx);return false;}const revision=Math.max(0,Number(current?.revision||0))+1,item={eventId:`${APP_ID}:${base.sourceHash}:r${revision}`,appId:APP_ID,sourceRecordId:base.sourceRecordId,revision,eventType:base.eventType,occurredAt:base.occurredAt,payload:base.payload,queuedAt:new Date().toISOString()};tx.objectStore('outbox').put(item);seen.put({sourceKey:key,appId:APP_ID,sourceRecordId:base.sourceRecordId,state:'queued',revision,fingerprint:base.fingerprint,at:new Date().toISOString()});await txDone(tx);return true;}finally{db.close();}}
export async function notifyKokugoEventSaved(event){try{if(!event?.id||!apiBase())return{queued:false,reason:'local_only'};if(await getControl('syncRevoked'))return{queued:false,reason:'revoked'};if(await getControl('collectionDisabled'))return{queued:false,reason:'ignored'};const pending=await ensurePendingRegistration();const base=await eventBase(event);if(baselineContains(pending,base))return{queued:false,reason:'baseline'};const queued=await queueEvent(base);if(queued)scheduleFlush();return{queued};}catch{return{queued:false,reason:'queue_failed'};}}
async function readOutbox(){const db=await openDb();try{const tx=db.transaction('outbox','readonly'),rows=await requestValue(tx.objectStore('outbox').getAll());await txDone(tx);return(rows||[]).filter(x=>x?.appId===APP_ID).sort((a,b)=>String(a.queuedAt).localeCompare(String(b.queuedAt))).slice(0,MAX_BATCH);}finally{db.close();}}
async function settleBatch(doneIds,rejected,batch){const done=new Set((doneIds||[]).map(String)),rejMap=new Map((rejected||[]).filter(x=>x?.eventId).map(x=>[String(x.eventId),x]));if(!done.size&&!rejMap.size)return;const byId=new Map(batch.map(x=>[String(x.eventId),x])),db=await openDb();try{const tx=db.transaction(['outbox','deadletter'],'readwrite'),o=tx.objectStore('outbox'),d=tx.objectStore('deadletter');for(const id of done)o.delete(id);for(const[id,row]of rejMap){d.put({eventId:id,code:String(row.code||'rejected'),rejectedAt:new Date().toISOString(),event:byId.get(id)||null});o.delete(id);}await txDone(tx);}finally{db.close();}}
async function uploadBaselineIfNeeded(){const reg=await getControl('registration');if(!reg?.credential)return false;const key=`${APP_ID}:baselineSent:${reg.registrationId}`;if(await getControl(key))return true;const pending=await getControl('pendingRegistration'),baseline=pending?.baseline||{summary:summarizeBaseline([]),fingerprints:[]};try{const r=await fetchWithTimeout(`${apiBase()}/v1/progress/snapshot`,{method:'PUT',headers:{'content-type':'application/json','authorization':`Bearer ${reg.credential}`},body:JSON.stringify({appId:APP_ID,generation:1,payload:baseline.summary})});const d=await r.json().catch(()=>({}));if(r.status===401){await setControl('syncRevoked',true);return false;}if(r.status===403&&d?.code==='collection_disabled'){await setControl('collectionDisabled',true);return false;}if(!r.ok)return false;await markBaselineSeen(baseline.fingerprints||[]);await setControl(key,{at:new Date().toISOString()});await setControl('pendingRegistration',null);return true;}catch{return false;}}
async function refreshControl(){const reg=await getControl('registration');if(!reg?.credential)return false;try{const r=await fetchWithTimeout(`${apiBase()}/v1/control`,{headers:{'authorization':`Bearer ${reg.credential}`}});const d=await r.json().catch(()=>({}));if(r.status===401){await setControl('syncRevoked',true);return false;}if(!r.ok)return false;await setControl('collectionDisabled',d.collectionEnabled===false);await setControl('registration',{...reg,status:d.status||reg.status,deviceCode:d.deviceCode||reg.deviceCode});return true;}catch{return false;}}
async function flushOnce(){if(await getControl('syncRevoked'))return true;let reg=await getControl('registration');if(!reg?.credential){if(!(await registerSilently()))return false;reg=await getControl('registration');}if(!reg?.credential||navigator.onLine===false)return false;if(await getControl('collectionDisabled'))return true;if(!(await uploadBaselineIfNeeded()))return false;const batch=await readOutbox();if(!batch.length)return true;const r=await fetchWithTimeout(`${apiBase()}/v1/events/batch`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${reg.credential}`},body:JSON.stringify({events:batch.map(({queuedAt,...e})=>e)})});const d=await r.json().catch(()=>({}));if(r.status===401){await setControl('syncRevoked',true);return true;}if(r.status===403&&d?.code==='collection_disabled'){await setControl('collectionDisabled',true);return true;}if(r.status===400&&d?.code==='no_valid_events'){await settleBatch([],d.rejected||[],batch);return true;}if(!r.ok)return false;await settleBatch([...(d.accepted||[]),...(d.duplicate||[])],d.rejected||[],batch);if(batch.length===MAX_BATCH)flushAgain=true;return true;}
export function flushProgressSync(){if(flushInFlight){flushAgain=true;return flushInFlight;}flushInFlight=(async()=>{try{const ok=await flushOnce();if(ok)flushBackoff=1000;else scheduleRetry();return ok;}catch{scheduleRetry();return false;}finally{flushInFlight=null;if(flushAgain){flushAgain=false;scheduleFlush();}}})();return flushInFlight;}
function scheduleFlush(){if(!flushTimer)flushTimer=setTimeout(()=>{flushTimer=null;void flushProgressSync();},FLUSH_DELAY_MS);}
function scheduleRetry(){if(flushTimer)return;const wait=flushBackoff+Math.floor(Math.random()*Math.max(250,flushBackoff*.25));flushBackoff=Math.min(MAX_BACKOFF_MS,flushBackoff*2);flushTimer=setTimeout(()=>{flushTimer=null;void syncCycle();},wait);}
async function reconcile(){if(typeof baselineProvider!=='function')return;for(const e of(await baselineProvider())||[]){if(!e?.id)continue;const base=await eventBase(e),pending=await getControl('pendingRegistration');if(baselineContains(pending,base))continue;await queueEvent(base);}}
async function syncCycle(){if(!apiBase()||await getControl('syncRevoked'))return;if(!(await registerSilently()))return;await refreshControl();if(await getControl('collectionDisabled'))return;if(!(await uploadBaselineIfNeeded()))return;await reconcile();scheduleFlush();}
function startScanner(){if(scannerStarted)return;scannerStarted=true;window.setInterval(()=>void syncCycle(),RECONCILE_INTERVAL_MS);void syncCycle();}
export function initKokugoProgressSync({loadExistingEvents}={}){if(loadExistingEvents)baselineProvider=loadExistingEvents;if(initPromise)return initPromise;initPromise=(async()=>{if(!apiBase())return{mode:'local-only'};try{await persistEnrollmentTokenFromHash();await ensurePendingRegistration();await registerSilently();startScanner();window.addEventListener('online',()=>void syncCycle());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')void syncCycle();});const reg=await getControl('registration');return{mode:reg?.credential?'cloud':'cloud-pending',status:reg?.status||'unclassified',deviceCode:reg?.deviceCode||null};}catch{startScanner();return{mode:'cloud-degraded'};}})();return initPromise;}

