import React,{useEffect,useRef,useState} from 'react';
import {loadDraft,saveRepairDraft} from './lib/localdb.js';
import {bridgeFeedback} from './nextExamCourse.js';
export default function NextExamBridge({set,onClose,onRepair}){
 const key=`draft:unit:${set.id}:r${set.revision}`;
 const [s,setS]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[notice,setNotice]=useState(''),[clock,setClock]=useState(Date.now());
 const current=useRef(null),lock=useRef(false);
 useEffect(()=>{let live=true;loadDraft(key).then(d=>{if(live){const state=d||{year:key,draftId:key,draftType:'learning-unit',unitId:set.id,revision:set.revision,generation:0,answers:{},flags:{},assessments:{},startedAt:Date.now()};current.current=state;setS(state);}}).catch(e=>setError(e.message));const t=setInterval(()=>setClock(Date.now()),1000);return()=>{live=false;clearInterval(t);};},[]);
 async function save(next){if(lock.current||conflict)return false;lock.current=true;setBusy(true);setNotice('');try{const r=await saveRepairDraft(key,{...next,savedAt:new Date().toISOString()},current.current.generation||0);if(r.conflict){setConflict(true);throw Error('別タブと競合しました。両方の答案を保持しました。再読み込みして確認してください。');}if(!r.saved)throw Error('保存できませんでした');current.current=r.record;setS(r.record);setNotice('端末に保存しました。');return true;}catch(e){setError(e.message);return false;}finally{lock.current=false;setBusy(false);}}
 function edit(patch){const next={...current.current,...patch};current.current=next;setS(next);setNotice('');}
 useEffect(()=>{if(!s||busy||conflict)return;const t=setTimeout(()=>save(current.current),800);return()=>clearTimeout(t);},[s?.answers,s?.flags]);
 useEffect(()=>{const guard=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[]);
 if(!s)return <main className="shell"><p>{error||'答案を読み込み中…'}</p></main>;
 const disabled=busy||conflict,submitted=!!s.submission,seconds=Math.max(0,Math.floor(((s.submission?.submittedAt||clock)-s.startedAt)/1000)),feedback=submitted?bridgeFeedback(set,s):[];
 return <main className="shell nextExamBridge"><header className="homeHeader"><h1>{set.title}</h1><button disabled={disabled} onClick={async()=>{if(await save(current.current))onClose();}}>保存して教材一覧へ</button></header><p role="alert">{error}</p><p role="status">{busy?'保存中…':notice}</p>
 <section className="card"><h2>読む・選ぶ・書くを組み合わせる</h2><p>学習用オリジナル。今日はこの3問と振り返りまで。12分は練習の目安です。最初の3分で本文と設問を確認し、次の7分で解き、最後の2分で保留と字数を見直す方法を試しましょう。</p><p>難しい問題は「保留して戻る」に印を付け、他の問題を先に解けます。空欄でもまとめて提出できます。答案を保存するまで解答例は表示しません。</p><p className="bridgeTimer">経過 {Math.floor(seconds/60)}分{seconds%60}秒／目安 {set.minutes}分（離席・保存中も含む）</p><p>{seconds>set.minutes*60?'目安を超えています。空欄や保留を確認して提出するか、学習として続けられます。':''}</p><p className="unitPassage">{set.text}</p></section>
 {set.questions.map((q,i)=><section className="card" key={q.id}><h2>問{i+1}</h2><p>{q.question}</p>{q.kind==='choice'?<fieldset disabled={disabled||submitted}><legend>一つ選択</legend>{q.options.map((o,j)=><label className="unitCriterion" key={o}><input type="radio" name={q.id} checked={s.answers[q.id]===j} onChange={()=>edit({answers:{...s.answers,[q.id]:j}})}/>{o}</label>)}<button onClick={()=>edit({answers:{...s.answers,[q.id]:''}})}>選択を取り消す</button></fieldset>:<><label>問{i+1}の答案<textarea aria-label={`問${i+1}の答案`} disabled={disabled||submitted} value={s.answers[q.id]||''} onChange={e=>edit({answers:{...s.answers,[q.id]:e.target.value}})}/></label><p>{[...String(s.answers[q.id]||'')].length}／{q.max}字</p></>}
 <label><input type="checkbox" disabled={disabled||submitted} checked={!!s.flags[q.id]} onChange={e=>edit({flags:{...s.flags,[q.id]:e.target.checked}})}/>問{i+1}を保留して戻る</label>
 {submitted&&<><p>結果：{feedback[i].status}</p><p>解答例：{q.kind==='choice'?q.options[q.correct]:q.model}</p><p>{q.explanation}</p>{q.kind==='written'&&q.criteria.map((c,j)=><label className="unitCriterion" key={c}>{c}<select aria-label={`問${i+1}の基準${j+1}`} disabled={disabled} value={s.assessments[q.id]?.[j]||''} onChange={e=>save({...current.current,assessments:{...current.current.assessments,[q.id]:{...current.current.assessments[q.id],[j]:e.target.value}}})}><option value="">未確認</option><option value="yes">できた</option><option value="no">不足・誤り</option><option value="uncertain">判断に迷う</option></select></label>)}</>}
 </section>)}
 <section className="card">{!submitted?<><button disabled={disabled} onClick={()=>save(current.current)}>途中保存</button><button disabled={disabled} onClick={()=>save({...current.current,submission:{answers:{...current.current.answers},flags:{...current.current.flags},submittedAt:Date.now()},exposure:'この本文を初めて開いたかは別途確認が必要'})}>3問の初回答案を保存して比較する</button></>:<><h2>次の勉強</h2><p>選択は正答との一致、記述は要素ごとの自己評価です。短いセットの結果を過去問得点へ換算しません。判断に迷う答案は保護者・指導者に見てもらいましょう。</p>{[...new Set(feedback.filter(f=>!['正答','自己評価で確認'].includes(f.status)).map(f=>f.skill))].map(skill=><p key={skill}><button disabled={disabled} onClick={async()=>{if(await save(current.current))onRepair(skill);}}>補強へ：{skill}</button></p>)}{feedback.every(f=>['正答','自己評価で確認'].includes(f.status))&&<p>このセットの確認を記録しました。別の未使用セット、またはホームから次の過去問へ進みましょう。</p>}<p>この本文は今後、既見の学習教材として扱います。初回答案は固定し、再提出で上書きしません。</p></>}</section></main>;
}

